document-meta:
  title: "ドキュメントタイトル"
  subtitle: "デジタル庁デザインシステム準拠テンプレート"
  author: ["作成者名"]
  affiliation: "所属・プロジェクト名"
  keywords: ["デジタル庁デザインシステム", "ドキュメントテンプレート"]
  date: auto

font-setting:
  sans-font: "Noto Sans"
  sans-font-cjk: "IPAexGothic"
  mono-font: "Noto Sans Mono"
  mono-font-cjk: "IPAexGothic"
  serif-font: "Noto Sans"
  serif-font-cjk: "IPAexGothic"
  
document-setting:
  columns: 1
  fig-tab-separator: ": "
  heading-numbering: "1.1 "
  show-header: true
  show-footer: true
